services:
  api:
    container_name: quizland_api 
    image: quizland-api:0.1.3
    build: ./quizland-gql
    ports:
      - "4000:4000"
    networks:
      quizland:
        ipv4_address: "172.18.1.10"
    restart: unless-stopped

  www:
    container_name: quizland_www
    image: quizland-www:0.1.1
    build: ./quizland-web
    ports:
      - "3000:3000"
    networks:
      quizland:
        ipv4_address: "172.18.1.20"
    restart: unless-stopped
    depends_on:
      - "api"

networks:
  quizland:
    ipam:
      driver: default
      config:
        - subnet: "172.18.1.0/24"
